---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-defrag
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: etcd-defrag-talosconfig
    template:
      type: Opaque
      data:
        config: "{{ .talosconfig }}"
  data:
    - secretKey: talosconfig
      remoteRef:
        key: talosconfig
