---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# Omada Controller secret — provides EAP_MONGOD_URI for external MongoDB connection
# AKV key: omada-controller  required properties: MONGODB_PASSWORD
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-controller
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: omada-controller-secret
    template:
      data:
        EAP_MONGOD_URI: "mongodb://omada:{{ .MONGODB_PASSWORD }}@omada-db-mongodb.database.svc.cluster.local:27017/omada?authSource=omada"
  dataFrom:
    - extract:
        key: omada-controller
