---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alert-triage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: alert-triage-secret
    template:
      data:
        GITHUB_TOKEN: "{{ .FLUX_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: flux
