---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: cilium-mcp
spec:
  image: ghcr.io/azure/mcp-kubernetes:v0.0.15@sha256:00f9368570147c74843bd7c5587aac33ebfd804ca6b956b4e7c793e4d8c19bd4
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount: cilium-mcp
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - --transport=streamable-http
            - --additional-tools=cilium,hubble
            - --host=0.0.0.0
            - --port=8000
  groupRef:
    name: mcp-tools
