---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: default
data:
  qbittorrent.conf: |
    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    Session\AddExtensionToIncompleteFiles=true
    Session\AnonymousModeEnabled=false
    Session\DefaultSavePath=/data/downloads
    Session\TempPath=/data/downloads/.incomplete
    Session\TempPathEnabled=true
    Session\GlobalMaxSeedingMinutes=0
    Session\GlobalMaxRatio=3
    Session\MaxActiveDownloads=5
    Session\MaxActiveTorrents=500
    Session\MaxActiveUploads=500
    Session\MaxConnections=2000
    Session\MaxConnectionsPerTorrent=200
    Session\MaxHalfOpenConnections=50
    Session\MaxUploads=50
    Session\MaxUploadsPerTorrent=16
    Session\Port=31288
    Session\Preallocation=false
    Session\QueueingSystemEnabled=true
    Session\uTP\RateLimited=true
    Session\Encryption=2
    Session\DHTEnabled=true
    Session\LSDEnabled=true
    Session\PeXEnabled=true
    Session\AnnounceToAllTrackers=true
    Session\AnnounceToAllTiers=true

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [Meta]
    MigrationVersion=6

    [Network]
    Proxy\Type=None

    [WebUI]
    Address=*
    AuthSubnetWhitelistEnabled=true
    AuthSubnetWhitelist=127.0.0.1/32, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
    BanDuration=0
    CSRFProtection=false
    ClickjackingProtection=false
    CustomHTTPHeadersEnabled=false
    HostHeaderValidation=false
    LocalHostAuth=false
    MaxAuthenticationFailCount=9999
    Port=80
    ReverseProxySupportEnabled=true
    ReverseProxyTrustedAddresses=10.0.0.0/8, 192.168.0.0/16
    SecureCookie=false
    ServerDomains=*
    SessionTimeout=3600
    Username=admin
