---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: qbittorrent-secret
    template:
      data:
        QBT_WEBUI_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        QBT_WEBUI_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: qbittorrent
