---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: mikrotik-exporter-secret
    template:
      data:
        MIKROTIK_USERNAME: "{{ .MIKROTIK_EXPORTER_USERNAME }}"
        MIKROTIK_PASSWORD: "{{ .MIKROTIK_EXPORTER_PASSWORD }}"
  dataFrom:
    - extract:
        key: mikrotik-exporter
