---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mikrotik-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    fullnameOverride: *app
    controllers:
      mktxp:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: busybox
              tag: 1.38.0
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                sed -e 's|$${MIKROTIK_USERNAME}|'"$MIKROTIK_USERNAME"'|g' \
                    -e 's|$${MIKROTIK_PASSWORD}|'"$MIKROTIK_PASSWORD"'|g' \
                    /config-template/mktxp.conf > /etc/mktxp/mktxp.conf
                cp /config-template/_mktxp.conf /etc/mktxp/_mktxp.conf
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
        containers:
          mktxp:
            image:
              repository: ghcr.io/akpw/mktxp
              tag: 1.2.20@sha256:f894f2457670ec76d57a8cea9cb8ac66bcd3e8e2360c85453b8f9ddb9390bfc7
            command:
              - "mktxp"
            args:
              - "--cfg-dir"
              - "/etc/mktxp"
              - "export"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      mktxp:
        ports:
          http:
            port: 49090
    serviceMonitor:
      mktxp:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config-template:
        type: configMap
        name: mktxp-config
        globalMounts:
          - path: /config-template/mktxp.conf
            subPath: mktxp.conf
          - path: /config-template/_mktxp.conf
            subPath: _mktxp.conf
      config:
        type: emptyDir
        globalMounts:
          - path: /etc/mktxp
