---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: netbox-secret
    template:
      data:
        secret_key: "{{ .NETBOX_SECRET_KEY }}"
        postgresql-password: "{{ .NETBOX_DB_PASSWORD }}"
        tasks-password: "{{ .NETBOX_REDIS_PASSWORD }}"
        cache-password: "{{ .NETBOX_REDIS_PASSWORD }}"
        username: "{{ .NETBOX_SUPERUSER_NAME }}"
        email: "{{ .NETBOX_SUPERUSER_EMAIL }}"
        password: "{{ .NETBOX_SUPERUSER_PASSWORD }}"
        api_token: "{{ .NETBOX_SUPERUSER_API_TOKEN }}"
        email_password: "{{ .NETBOX_EMAIL_PASSWORD | default \"\" }}"
  dataFrom:
    - extract:
        key: netbox
