---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: autobrr-secret
    template:
      data:
        AUTOBRR__SESSION_SECRET: "{{ index . \"AUTOBRR_SESSION_SECRET\" | default \"\" }}"
        AUTOBRR_BOOTSTRAP_USERNAME: "{{ index . \"AUTOBRR_BOOTSTRAP_USERNAME\" | default \"\" }}"
        AUTOBRR_BOOTSTRAP_PASSWORD: "{{ index . \"AUTOBRR_BOOTSTRAP_PASSWORD\" | default \"\" }}"
        AUTOBRR_QBITTORRENT_USERNAME: "{{ index . \"AUTOBRR_QBITTORRENT_USERNAME\" | default \"\" }}"
        AUTOBRR_QBITTORRENT_PASSWORD: "{{ index . \"AUTOBRR_QBITTORRENT_PASSWORD\" | default \"\" }}"
        # Tracker IRC credentials
        BLUTOPIA_PASSKEY: "{{ index . \"BLUTOPIA_PASSKEY\" | default \"\" }}"
        BLUTOPIA_IRC_PASSWORD: "{{ index . \"BLUTOPIA_IRC_PASSWORD\" | default \"\" }}"
        FEARNOPEER_AUTHKEY: "{{ index . \"FEARNOPEER_AUTHKEY\" | default \"\" }}"
        FEARNOPEER_IRC_PASSWORD: "{{ index . \"FEARNOPEER_IRC_PASSWORD\" | default \"\" }}"
        UPLOADCX_INFOHASH: "{{ index . \"UPLOADCX_INFOHASH\" | default \"\" }}"
        UPLOADCX_IRC_PASSWORD: "{{ index . \"UPLOADCX_IRC_PASSWORD\" | default \"\" }}"
  dataFrom:
    - extract:
        key: autobrr
