---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: grafana-mcp-secret
    template:
      data:
        GRAFANA_SERVICE_ACCOUNT_TOKEN: "{{ .GRAFANA_MCP_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana