---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onshape-mcp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: onshape-mcp-secret
    template:
      data:
        ONSHAPE_ACCESS_KEY: "{{ .ONSHAPE_ACCESS_KEY }}"
        ONSHAPE_SECRET_KEY: "{{ .ONSHAPE_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: onshape-mcp
