---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: toolhive-secret
    creationPolicy: Owner
    template:
      data:
        # OIDC
        entra-client-secret: "{{ .entra-client-secret }}"
  dataFrom:
    - extract:
        key: toolhive
