---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: hass-mcp
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:8.4.2@sha256:e7ef0dd68cc9bf44665e4ec9302fd6246b5d39c9ef86931c848c95bc3404b7f7
  transport: streamable-http
  env:
    - name: HOMEASSISTANT_URL
      value: https://hass.homeops.ca
  secrets:
    - name: hass-mcp-secret
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  groupRef:
    name: mcp-tools
