---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: hass-mcp
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:8.4.1@sha256:7823b36587a6e62efed271b26f3f72380b49f47364e5385580584e7ab2c60722
  transport: streamable-http
  env:
    - name: HOMEASSISTANT_URL
      value: https://hass.homeops.ca
  secrets:
    - name: hass-mcp-secret
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  groupRef:
    name: mcp-tools
