---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox
spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/zeroscaler
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/default/netbox/app
  postBuild:
    substitute:
      APP: netbox
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: true
