---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name speedtest-exporter
spec:
  scrapeInterval: 1h
  scrapeTimeout: 1m
  staticConfigs:
    - targets:
        - speedtest-exporter.observability.svc.cluster.local:9798
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name