---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: opnsense-secret
    template:
      data:
        # Reuses the same gw01 API credentials as the opnsense-exporter.
        OPNSENSE_API_KEY: "{{ .OPS_API_KEY }}"
        OPNSENSE_API_SECRET: "{{ .OPS_API_SECRET }}"
  dataFrom:
    - extract:
        key: opnsense-exporter
