---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# AKV key: librenms — must contain:
#   LIBRENMS_DB_PASSWORD, LIBRENMS_DB_USERNAME, LIBRENMS_APP_KEY
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librenms
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: librenms-secret
    template:
      data:
        DB_USERNAME: "{{ .LIBRENMS_DB_USERNAME }}"
        DB_PASSWORD: "{{ .LIBRENMS_DB_PASSWORD }}"
        APP_KEY: "{{ .LIBRENMS_APP_KEY }}"
  dataFrom:
    - extract:
        key: librenms
