---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: pve-exporter-secret
    template:
      data:
        PVE_USER: "{{ .PVE_EXPORTER_USER }}"
        PVE_TOKEN_NAME: "{{ .PVE_EXPORTER_TOKEN_NAME }}"
        PVE_TOKEN_VALUE: "{{ .PVE_EXPORTER_TOKEN_VALUE }}"
  dataFrom:
    - extract:
        key: pve-exporter
