---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unbound-dns-certs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: unbound-dns-certs-secret
    template:
      data:
        unbound_server.pem: "{{ .UNBOUND_CA_PEM }}"
        unbound_control.pem: "{{ .UNBOUND_CERT_PEM }}"
        unbound_control.key: "{{ .UNBOUND_KEY_PEM }}"
  dataFrom:
    - extract:
        key: unbound
