---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unbound-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: unbound-dns-secret
    template:
      data:
        UNBOUND_CA_PEM_PATH: "{{ .UNBOUND_CA_PEM_PATH }}"
        UNBOUND_CERT_PEM_PATH: "{{ .UNBOUND_CERT_PEM_PATH }}"
        UNBOUND_KEY_PEM_PATH: "{{ .UNBOUND_KEY_PEM_PATH }}"
  dataFrom:
    - extract:
        key: unbound
