---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-mcp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: omada-mcp-secret
    template:
      data:
        OMADA_BASE_URL: "{{ .omada_base_url }}"
        OMADA_CLIENT_ID: "{{ .omada_client_id }}"
        OMADA_CLIENT_SECRET: "{{ .omada_client_secret }}"
        OMADA_OMADAC_ID: "{{ .omada_omadac_id }}"
  dataFrom:
    - extract:
        key: omada-mcp
