---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mqtt-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      mqtt-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/kpetremann/mqtt-exporter
              tag: 1.12.1@sha256:dca3255f35310f6ceb80ed1de94eebd1fe9def7aacaec4107fe37cdaa9eb3be0
            env:
              MQTT_ADDRESS: mosquitto.default.svc.cluster.local
              MQTT_V5_PROTOCOL: true
              PROMETHEUS_PORT: &port 3321
              TZ: "America/Toronto"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 200Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          metrics:
            protocol: HTTP
            port: *port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            metricRelabelings:
              - action: labeldrop
                regex: "endpoint|container|job|instance|pod|prometheus|namespace"
              - action: replace
                sourceLabels:
                  - "service"
                targetLabel: instance
