---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azurekv
spec:
  provider:
    azurekv:
      vaultUrl: "https://keyvault-kube.vault.azure.net"
      tenantId: "2dd2129b-675b-4350-a458-0147ce24617a"
      authSecretRef:
        tenantId:
          name: azurekv-secret
          namespace: external-secrets
          key: tenantId
        clientId:
          name: azurekv-secret
          namespace: external-secrets
          key: clientId
        clientSecret:
          name: azurekv-secret
          namespace: external-secrets
          key: clientSecret
