---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azurekv
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: azurekv-secret
    template:
      data:
        tenantId: "{{ .AZURE_TENANT_ID }}"
        clientId: "{{ .AZURE_CLIENT_ID }}"
        clientSecret: "{{ .AZURE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: azurekv
