---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thelounge-config
  namespace: default
data:
  config.js: |
    "use strict";

    module.exports = {
      // Server host and port
      host: "0.0.0.0",
      port: 9000,
      bind: undefined,

      // Default theme
      theme: "morning",

      // Prefetch setting for thumbnails and Link Previewer
      prefetch: false,

      // Settings for the `Unread message marker` feature
      defaults: {
        name: "Thelounge",
        nick: "autobrr",
      },

      // Maximum number of concurrent connections per host
      maxConnections: 1,

      // Maximum socket lifetime in milliseconds
      socketTimeout: 600000,

      // Whether to log raw message objects
      messageLogging: false,

      // Color coding log levels
      colors: {
        date: "gray",
        error: "red",
        warn: "yellow",
        info: "cyan",
        debug: "green",
        trace: "magenta",
      },

      // Whether to log IP addresses
      logIpAddresses: false,

      // Whether to log hostmasks
      logHostnames: true,

      // List of reverse proxy headers that should be trusted
      reverseProxy: true,
      trustedProxies: ["10.42.0.0/16", "192.168.69.0/24", "127.0.0.1"],

      // Auto-connect to these networks on startup
      defaults: {
        name: "Tracker Networks",
        nick: "autobrr_bot",
      },
    };

  networks.json: |
    [
      {
        "uuid": "blutopia-net",
        "name": "Blutopia",
        "host": "irc.blutopia.xyz",
        "port": 6697,
        "tls": true,
        "rejectUnauthorized": false,
        "nick": "your_blutopia_nick",
        "username": "your_blutopia_nick",
        "realName": "Autobrr Bot",
        "join": ["#announce", "#general"],
        "sasl": false,
        "saslMechanism": "PLAIN",
        "password": "",
        "away": "Away"
      },
      {
        "uuid": "fearnopeer-net",
        "name": "fearnopeer",
        "host": "irc.fearnopeer.com",
        "port": 6697,
        "tls": true,
        "rejectUnauthorized": false,
        "nick": "your_fearnopeer_nick",
        "username": "your_fearnopeer_nick",
        "realName": "Autobrr Bot",
        "join": ["#announce", "#general"],
        "sasl": false,
        "password": "",
        "away": "Away"
      },
      {
        "uuid": "uploadcx-net",
        "name": "upload.cx",
        "host": "irc.upload.cx",
        "port": 6697,
        "tls": true,
        "rejectUnauthorized": false,
        "nick": "your_uploadcx_nick",
        "username": "your_uploadcx_nick",
        "realName": "Autobrr Bot",
        "join": ["#announce", "#general"],
        "sasl": false,
        "password": "",
        "away": "Away"
      }
    ]
