---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas01
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      bucket: default-bucket
      endpoint: 192.168.42.45:3900
      region: us-east-1
      prefix: home-ops/
      tls:
        disableTls: true
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: kopiur-system
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  maintenance:
    schedule:
      quick:
        cron: 0 * * * *
        jitter: 10m
      full:
        cron: 0 3 * * *
        jitter: 1h
  moverDefaults:
    cache:
      capacity: 1Mi
      mode: Ephemeral
      storageClassName: openebs-hostpath
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    scratch:
      capacity: 1Mi
      storageClassName: openebs-hostpath
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    ttlSecondsAfterFinished: 300
  scheduleDefaults:
    timezone: America/Toronto
