---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: opnsense-exporter-secret
    template:
      data:
        OPS_API_KEY: "{{ .OPS_API_KEY }}"
        OPS_API_SECRET: "{{ .OPS_API_SECRET }}"
  dataFrom:
    - extract:
        key: opnsense-exporter
