---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
spec:
  chartRef:
    kind: OCIRepository
    name: unpackerr
  interval: 1h
  values:
    controllers:
      unpackerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.15.2@sha256:89e13608521ece21dd300c39229fd595a55fbf4b8152771af5670a7455b5c747
            env:
              TZ: America/Toronto
              # Lidarr
              UN_LIDARR_0_URL: http://lidarr.default.svc.cluster.local
              UN_LIDARR_0_PATHS_0: /data/downloads/torrents/complete
              UN_LIDARR_0_PROTOCOLS: torrent
              UN_LIDARR_0_TIMEOUT: 10s
              UN_LIDARR_0_DELETE_DELAY: 5m
              UN_LIDARR_0_DELETE_ORIG: false
              # Radarr
              UN_RADARR_0_URL: http://radarr.default.svc.cluster.local
              UN_RADARR_0_PATHS_0: /data/downloads/torrents/complete
              UN_RADARR_0_PROTOCOLS: torrent
              UN_RADARR_0_TIMEOUT: 10s
              UN_RADARR_0_DELETE_DELAY: 5m
              UN_RADARR_0_DELETE_ORIG: false
              # Sonarr
              UN_SONARR_0_URL: http://sonarr.default.svc.cluster.local
              UN_SONARR_0_PATHS_0: /data/downloads/torrents/complete
              UN_SONARR_0_PROTOCOLS: torrent
              UN_SONARR_0_TIMEOUT: 10s
              UN_SONARR_0_DELETE_DELAY: 5m
              UN_SONARR_0_DELETE_ORIG: false
              # Whisparr
              UN_WHISPARR_0_URL: http://whisparr.default.svc.cluster.local
              UN_WHISPARR_0_PATHS_0: /data/downloads/torrents/complete
              UN_WHISPARR_0_PROTOCOLS: torrent
              UN_WHISPARR_0_TIMEOUT: 10s
              UN_WHISPARR_0_DELETE_DELAY: 5m
              UN_WHISPARR_0_DELETE_ORIG: false
            envFrom:
              - secretRef:
                  name: unpackerr-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      media:
        type: nfs
        server: nas02.in.homeops.ca
        path: /volume1/data
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
