---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Cloudflare Tunnel Ready
    group: services
    url: http://cloudflare-tunnel.network.svc.cluster.local:8080/ready
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: Plex Backend Identity
    group: services
    url: http://plex.default.svc.cluster.local:32400/identity
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  # Out-of-Band Management Infrastructure
  - name: PiKVM (kvm01)
    group: oob-management
    url: https://kvm01.in.homeops.ca
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    client:
      insecure: true

  - name: PDU01
    group: oob-management
    url: tcp://pdu01.in.homeops.ca:161
    interval: 2m
    conditions:
      - "[CONNECTED] == true"

  - name: PDU02
    group: oob-management
    url: tcp://pdu02.in.homeops.ca:161
    interval: 2m
    conditions:
      - "[CONNECTED] == true"

  - name: UPS01
    group: oob-management
    url: tcp://ups01.in.homeops.ca:161
    interval: 2m
    conditions:
      - "[CONNECTED] == true"

  - name: UPS02
    group: oob-management
    url: tcp://ups02.in.homeops.ca:161
    interval: 2m
    conditions:
      - "[CONNECTED] == true"

  - name: ConsolePi (pi02)
    group: oob-management
    url: tcp://192.168.42.22:22
    interval: 2m
    conditions:
      - "[CONNECTED] == true"

  - name: ConsolePi (pi03)
    group: oob-management
    url: tcp://192.168.42.23:22
    interval: 2m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/18647660
  link: https://github.com/osnabrugge
  buttons:
    - name: Github
      link: https://github.com/osnabrugge
    - name: Homelab
      link: https://github.com/osnabrugge/home-ops

web:
  port: ${GATUS_WEB_PORT}
