---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Cloudflare Tunnel Ready
    group: services
    url: http://cloudflare-tunnel.network.svc.cluster.local:8080/ready
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: Plex Routed Identity
    group: external
    url: https://envoy-network-envoy-external-27f017ad.network.svc.cluster.local/identity
    interval: 1m
    client:
      insecure: true
      timeout: 10s
      headers:
        Host: plex.homeops.ca
    conditions:
      - "[STATUS] == 200"
      - "[STATUS] == 401"
      - "[STATUS] == 301"
      - "[STATUS] == 302"

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/18647660
  link: https://github.com/osnabrugge
  buttons:
    - name: Github
      link: https://github.com/osnabrugge
    - name: Homelab
      link: https://github.com/osnabrugg/home-ops

web:
  port: ${GATUS_WEB_PORT}
