{
 "title": "UPS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(globalSystemStatus, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server basic information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(processorDeviceIndex{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "systemPowerState{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "DISK ISSUES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "physicalDiskComponentStatus{service=\"$service\"} == 4"
    }
   ]
  },
  {
   "title": "CONTROLLER BATTERY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "systemStateBatteryStatusCombined{service=\"$service\"} != 3"
    }
   ]
  },
  {
   "title": "PS1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powerSupplyStatus{service=\"$service\", powerSupplyIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "amperageProbeReading{service=\"$service\"} > 20"
    }
   ]
  },
  {
   "title": "CORES",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "PS2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powerSupplyStatus{service=\"$service\", powerSupplyIndex=\"2\"}"
    }
   ]
  },
  { "title": "Server temperature sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server temperature sensors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(temperatureProbeReading{service=\"$service\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{service=\"$service\"})",
     "legendFormat": "{{temperatureProbeLocationName}}"
    },
    {}
   ]
  },
  { "title": "Server hard disk information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Panel Title",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{service=\"$service\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{service=\"$service\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{service=\"$service\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{service=\"$service\"}) "
    },
    {
     "expr": "physicalDiskComponentStatus{service=\"$service\"}"
    }
   ]
  }
 ]
}