---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/alerts
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./blackbox-exporter/ks.yaml
  - ./gatus-sidecar/ks.yaml
  - ./grafana-operator/ks.yaml
  - ./kromgo/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./opnsense-exporter/ks.yaml
  - ./prometheus-adapter/ks.yaml
  - ./pve-exporter/ks.yaml
  - ./radar/ks.yaml
  - ./silence-operator/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./snmp-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./netbox-operator/ks.yaml
  - ./netbox/ks.yaml
  - ./netbox-diode/ks.yaml
  - ./victoria-logs/ks.yaml
