---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-operator
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: netbox-operator-secret
    template:
      data:
        api_token: "{{ .NETBOX_SUPERUSER_API_TOKEN }}"
  dataFrom:
    - extract:
        key: netbox
