apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: auth
type: Opaque
stringData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:0+wo/y7y0lLtNMuDoqdQSReg,iv:POkQ9Yxkq0/94C8X30MumIvYUetGvtVrAWRoyANEyYU=,tag:4lWOG4rYKhbAZMzqNeg9RA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:/bl2FFWlDmo10beErS/a7YYT20niQI7z4CA1GZrCzi9p4ZFraf9rINZPnvmqnFZkP7WlBC0vl27WfSmujs8TfQ==,iv:sbjqRm2axYTJWFYpKjaPXr7BBYyvyBjmxRjeY7UEkHQ=,tag:sxt1bUDeBwXbYkBqw87H8w==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:zBJAr7AxoL/T2OVwIurEK0nJHiby/pKh+nAmGksq4Ka/IOpQxcmWfg==,iv:aPJ9YTa8HoK+/SWh6xI8w+5w+E9nKJ0cpxVU9XLxPw0=,tag:uzRlaIY9VrhD5QKW1rwlAA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:kxVTx6nlyCz2sUt+Q912les25vVfjKMEs0eQoMo5xhKX6QkfrZnct9eyMycZww8Jqgcgo5jJiQSSOaGNj2lDqjjELyznksDzhuo3CAVAEwI=,iv:6ORrSkQHCbbFL4FAtlOy4zx4bOs7IrHdX1Oz+Vvo+KA=,tag:L9BTAMqkL/avzx286BDQGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdlBFZHU0K1dlMitPTW0w
            bFFGSk84L2o2WTJxQjBTZEhmYXlZQzd0MUd3CnJZSEhqVVhiOUhMeEk2VERvWnJD
            YysrQ0E3UU9BdU54MWpZL1ZHcVZqSWcKLS0tIEx2RDZTaDFqOG9WVHJDMXFiSDIr
            QWxXMFl5YUZUZnc1RFRXMUlDdlRDNGMKojtdpZqPUyRUwbdqDFXjaYh5Auohe3Da
            KpFnqGM7Rt73upF7hJLH1mdD/eTyH0VhBIPgTpFErWCtGXdjgqyv/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq3xj6j6qvfq4x55yzwr67myz0k3j3gjf8amtp3zz7hmxc4daq8qt677g5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T15:04:54Z"
    mac: ENC[AES256_GCM,data:SOcoLjwYs8XB5trUuiBElMRTtFJ726zZauL3S+eZDdIJZTHy9Uo0dD0ui4Mykm4kZ9fLyyowNKvX93YSYXnym0pcel0lX2xCXVnZ3/zn5AaIJsB629CIBjZjgen2lGqeU6vKwVIT7r6j1YSeXV9w2INqbLZWU9WjmE+lx6pOoVU=,iv:guq2eMA7LAPLfQTmyZw2DiUgDUGtnW0rJsjBSrnvY/A=,tag:wBp5zwl+ok/3O/ohV/cbpw==,type:str]
    version: 3.13.3
