{
 "title": "NAS Overview",
 "description": "The NAS Overview dashboard gives an overall glance at multiple NAS systems and their operational status.",
 "tags": [
  "NAS",
  "dsm"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "NASDevices", "query": "${VAR_NASDEVICES}" },
   { "name": "JobName", "query": { "query": "label_values(ssCpuUser, job)" } },
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$JobName'})"
    }
   },
   {
    "name": "InterfacePhysical",
    "label": "Network Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "InterfaceVirtual",
    "label": "Virtual Interfaces",
    "query": {
     "query": "label_values(ifType_info{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "raidName",
    "label": "Storage",
    "query": {
     "query": "label_values(raidName{job=~'$JobName',instance=~'$Device'},raidName)"
    }
   },
   {
    "name": "DiskName",
    "label": "Disk",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "DiskNameSSD",
    "label": "Cache",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   }
  ]
 },
 "panels": [
  { "title": "NAS Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NAS Systems",
   "type": "stat",
   "description": "Update the NASDevices variable with the total number of NAS systems you have in Prometheus regardless of the Job they are assigned to.  This is to help identify a NAS across the entire fleet.  It is meant to give you an idea that there is a problem regardless of which NAS device it is or the Prometheus Job it is in.\n\n\"Total NAS devices\" is the number of NAS devices you are reporting in Prometheus.  This is a number that you must manually enter in the NASDevices variable.  Count every NAS you have in Prometheus regardless of the Job it is in.\n\n\"NAS devices Down\" indicates that a NAS is either down or not being scrapped in either this Job or any other Job.\n\n\"Update Variable\" indicates that you are scrapping more NAS devices than you have entered in the NASDevices variable indicating a new device has come online.  Update the NASDevices variable to properly reflect the number of NAS devices you expect to be reporting on.\n",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "$NASDevices", "legendFormat": "Total NAS devices" },
    {
     "expr": "$NASDevices-count(systemStatus)>0",
     "legendFormat": "NAS devices Down"
    },
    {
     "expr": "count(systemStatus)-$NASDevices>0",
     "legendFormat": "Update Variable"
    }
   ]
  },
  {
   "title": "Network Interface Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2) >0",
     "legendFormat": "Admin Down"
    },
    {
     "expr": "(count(ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2)) - (count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2)) >0",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Storage Volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})",
     "legendFormat": "Total Storage"
    },
    {
     "expr": "count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=2 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=10) or (raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=13 and {job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=20))",
     "legendFormat": "RAID Warning"
    },
    {
     "expr": "count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=11 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=12) or raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>21)",
     "legendFormat": "RAID Failure"
    }
   ]
  },
  {
   "title": "Hard Drives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'})",
     "legendFormat": "Total Drives"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=2) and count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}<=3)",
     "legendFormat": "Not Used"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=4)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Cache Drives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'})",
     "legendFormat": "Total Drives"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}==3)>0",
     "legendFormat": "Not Used"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}>=4)>0",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "S.M.A.R.T Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}==1)",
     "legendFormat": "SMART Checks"
    },
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}==1)",
     "legendFormat": "SMART Failures"
    }
   ]
  },
  { "title": "NAS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "System Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "modelName{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "version{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "serialNumber{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "sysUpTime{job=~'$JobName',instance=~'$Device'}/100",
     "legendFormat": "UpTime"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "upgradeAvailable{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "cpuFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "(temperature{job=~'$JobName',instance=~'$Device'}*9/5)+32"
    },
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}+1"
    }
   ]
  },
  { "title": "S.M.A.R.T Disk Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "S.M.A.R.T Disk Failures",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}",
     "legendFormat": "AttrStatus"
    },
    {
     "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "InfoDevName"
    },
    {
     "expr": "diskSMARTAttrName{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "AttrName"
    },
    {
     "expr": "diskSMARTAttrCurrent{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "AttrCurrent"
    },
    {
     "expr": "diskSMARTAttrThreshold{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "AttrThreshold"
    },
    {
     "expr": "diskSMARTAttrWorst{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "AttrWorst"
    }
   ]
  },
  { "title": "Storage Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Storage Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}",
     "legendFormat": "Total Size"
    },
    {
     "expr": "(raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}-raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})",
     "legendFormat": "Used"
    },
    {
     "expr": "raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}",
     "legendFormat": "Free"
    },
    {
     "expr": "raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}",
     "legendFormat": "Free"
    },
    {
     "expr": "((raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}-raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})/raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})*100",
     "legendFormat": "Usage by Percent"
    }
   ]
  },
  { "title": "Drive  Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Hard Drive and SSD Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'} or diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}"
    },
    {
     "expr": "diskID{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'} or diskID{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'} "
    },
    {
     "expr": "diskType{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'} or diskType{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}"
    },
    {
     "expr": "diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'} or diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}"
    },
    {
     "expr": "diskModel{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'} or diskModel{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}"
    },
    {
     "expr": "(diskTemperature{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}*9/5)+32 or (diskTemperature{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}*9/5)+32"
    }
   ]
  },
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Physical Network Interface Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}"
    },
    {
     "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}"
    },
    {
     "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}"
    },
    {
     "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}"
    },
    {
     "expr": "ifAlias{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}"
    },
    {
     "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}"
    }
   ]
  },
  {
   "title": "Bond/Virtual Network Interface Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifAlias{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    }
   ]
  }
 ]
}