---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: hass-mcp
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:8.5.0@sha256:e1538bcdadb13a5467bbb8258fba3262a05518585e18115742da638adec7057c
  transport: streamable-http
  env:
    - name: FASTMCP_CHECK_FOR_UPDATES
      value: "off"
    - name: HOMEASSISTANT_URL
      value: http://home-assistant.default.svc.cluster.local:8123
    - name: HA_MCP_CONFIG_DIR
      value: /config
    - name: HA_MCP_DISABLE_UPDATE_CHECK
      value: "true"
    - name: MCP_HEALTHZ
      value: "true"
    - name: MCP_HOST
      value: 0.0.0.0
    - name: MCP_PORT
      value: "80"
    - name: TZ
      value: America/Toronto
  secrets:
    - name: hass-mcp-secret
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  groupRef:
    name: mcp-tools
