---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: frigate-secret
    template:
      data:
        FRIGATE_RTSP_PASSWORD: "{{ .FRIGATE_RTSP_PASSWORD }}"
  dataFrom:
    - extract:
        key: frigate
