---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mikrotik-mcp
spec:
  image: ghcr.io/jeff-nasseri/mikrotik-mcp:0.15.0@sha256:8f7a6a0eaed1727517a1e592024de27efe52bc54b95e8272ff9781f04a292463
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: MIKROTIK_HOST
      value: "192.168.99.24"
    - name: MIKROTIK_PORT
      value: "22"
    - name: MIKROTIK_MCP__TRANSPORT
      value: "streamable-http"
    - name: MIKROTIK_MCP__HOST
      value: "0.0.0.0"
    - name: MIKROTIK_MCP__PORT
      value: "8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          envFrom:
            - secretRef:
                name: mikrotik-mcp-secret
  resources:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      memory: 256Mi
  groupRef:
    name: mcp-tools
