---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whisparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
  target:
    name: whisparr-secret
    template:
      data:
        WHISPARR__AUTH__APIKEY: "{{ .WHISPARR_API_KEY }}"
  dataFrom:
    - extract:
        key: whisparr
