---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  chartRef:
    kind: OCIRepository
    name: whisparr
  interval: 1h
  values:
    controllers:
      whisparr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/whisparr
              tag: 2.0.0.2151@sha256:4b8aeb512fa872f5576634ab283c355535351e05fc0b3b26dd4b1962936c5e2d
            env:
              WHISPARR__APP__INSTANCENAME: Whisparr
              WHISPARR__APP__THEME: dark
              WHISPARR__AUTH__METHOD: External
              WHISPARR__AUTH__REQUIRED: DisabledForLocalAddresses
              WHISPARR__LOG__DBENABLED: "False"
              WHISPARR__LOG__LEVEL: info
              WHISPARR__SERVER__PORT: &port 80
              TZ: America/Toronto
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.homeops.ca"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: nas02.in.homeops.ca
        path: /volume1/data
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
