---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  main:
    name: Labeler - Labeler
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    environment: "Github Action Runner"
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Load Secrets
        id: load-secrets
        run: |
          SECRET=$(az keyvault secret show \
            --vault-name ${{ secrets.KEYVAULT_NAME }} \
            --name github-bot \
            --query value -o tsv)

          PRIVATE_KEY=$(echo "$SECRET" | jq -r '.GITHUB_BOT_APP_PRIVATE_KEY_B64' | base64 -d)
          echo "::add-mask::$PRIVATE_KEY"

          echo "GITHUB_BOT_APP_CLIENT_ID=$(echo "$SECRET" | jq -r '.GITHUB_BOT_APP_CLIENT_ID')" >> $GITHUB_OUTPUT
          {
            echo "GITHUB_BOT_APP_PRIVATE_KEY<<PEM_EOF"
            echo "$PRIVATE_KEY"
            echo "PEM_EOF"
          } >> $GITHUB_OUTPUT

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ steps.load-secrets.outputs.GITHUB_BOT_APP_CLIENT_ID }}
          private-key: ${{ steps.load-secrets.outputs.GITHUB_BOT_APP_PRIVATE_KEY }}

      - name: Labeler
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          configuration-path: .github/labeler.yaml
