---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app printguard
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      printguard:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/oliverbravery/printguard
              tag: latest
            env:
              TZ: America/Toronto
              HF_HOME: /data/huggingface
              XDG_DATA_HOME: /data
              XDG_CACHE_HOME: /data/cache
            envFrom:
              - secretRef:
                  name: printguard-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 8000
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.homeops.ca"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
